services:

  jacoco:
    build:
      context: .
      dockerfile: dockerfile
      target: jacocoweb # eliges la imagen a crear
    volumes:
      - ./web/nginx/sites-jacoco:/etc/nginx/sites-available # archivos de configuración de hosts virtuales
    restart: always # reinicio automático
    networks:
      - webnet # red de contenedores

  webtest:
    build:
      context: .
      dockerfile: dockerfile
      target: testweb
    volumes:
      - ./web/nginx/sites-test:/etc/nginx/sites-available # archivos de configuración de hosts virtuales
    restart: always # reinicio automático
    networks:
      - webnet # red de contenedores

  documentacion:
    build:
      context: .
      dockerfile: dockerfile
      target: docweb
    volumes:
      - ./web/apache/sites-available:/etc/apache2/sites-available # archivos de configuración de hosts virtuales
      - ./web/apache/website:/var/www/html/ # directorio de los sitios web
    restart: always # reinicio automático
    networks:
      - webnet # red de contenedores

  proxy:
    image: ubuntu/nginx # imagen de Nginx
    #container_name: proxy_server # nombre del contenedor
    ports:
      - "80:80" # mapeo de puertos  HTTP
      - "443:443" # mapeo de puertos  HTTPS
    volumes:
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf # archivo de configuración principal
      - ./proxy/certs:/etc/nginx/certs # directorio de certificados (hechos con openssl)
    restart: always # reinicio automático
    depends_on:
      - jacoco
      - webtest
      - documentacion
      - api
    networks:
      - webnet # red de contenedores

  api:
    build:
      context: .
      dockerfile: dockerfile
      target: run
    volumes:
      - ./storage-dir:/app/storage-dir
    restart: always
    env_file: .env
    depends_on:
      - mongo
      - redis
    networks:
      - webnet

  mongo:
    image: mongo:5.0
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./database/tienda.js:/docker-entrypoint-initdb.d/tienda.js
      - mongo-data:/data/db
    networks:
      - webnet

  redis:
    image: redis:7-alpine
    restart: always
    env_file: .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - webnet

    # PostgresSQL
  postgres:
    image: postgres:12-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
volumes:
  storage-dir:
  mongo-data:
  redis-data:
  postgres-data: